"""empty message

Revision ID: 86baf1389f8d
Revises: e674549c7e4b
Create Date: 2025-08-12 13:37:24.065209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86baf1389f8d'
down_revision = 'e674549c7e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=100),
                              type_=sa.String(length=50),
                              existing_nullable=False)
        batch_op.alter_column('image',
                              existing_type=sa.VARCHAR(length=200),
                              type_=sa.String(length=120),
                              existing_nullable=True)
        batch_op.alter_column('attributes',
                              existing_type=sa.VARCHAR(),
                              type_=postgresql.JSONB(astext_type=sa.Text()),
                              existing_nullable=True,
                              postgresql_using='attributes::jsonb')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=100),
                              type_=sa.String(length=50),
                              existing_nullable=False)
        batch_op.alter_column('image',
                              existing_type=sa.VARCHAR(length=200),
                              type_=sa.String(length=120),
                              existing_nullable=True)
        batch_op.alter_column('attributes',
                              existing_type=sa.VARCHAR(),
                              type_=postgresql.JSONB(astext_type=sa.Text()),
                              existing_nullable=True,
                              postgresql_using='attributes::jsonb')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
                              existing_type=sa.VARCHAR(length=128),
                              type_=sa.String(length=50),
                              existing_nullable=False)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=100),
                              type_=sa.String(length=50),
                              existing_nullable=False)
        batch_op.alter_column('image',
                              existing_type=sa.VARCHAR(length=200),
                              type_=sa.String(length=120),
                              existing_nullable=True)
        batch_op.alter_column('attributes',
                              existing_type=sa.VARCHAR(),
                              type_=postgresql.JSONB(astext_type=sa.Text()),
                              existing_nullable=True,
                              postgresql_using='attributes::jsonb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('attributes',
                              existing_type=postgresql.JSONB(
                                  astext_type=sa.Text()),
                              type_=sa.VARCHAR(),
                              existing_nullable=True)
        batch_op.alter_column('image',
                              existing_type=sa.String(length=120),
                              type_=sa.VARCHAR(length=200),
                              existing_nullable=True)
        batch_op.alter_column('name',
                              existing_type=sa.String(length=50),
                              type_=sa.VARCHAR(length=100),
                              existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
                              existing_type=sa.String(length=50),
                              type_=sa.VARCHAR(length=128),
                              existing_nullable=False)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('attributes',
                              existing_type=postgresql.JSONB(
                                  astext_type=sa.Text()),
                              type_=sa.VARCHAR(),
                              existing_nullable=True)
        batch_op.alter_column('image',
                              existing_type=sa.String(length=120),
                              type_=sa.VARCHAR(length=200),
                              existing_nullable=True)
        batch_op.alter_column('name',
                              existing_type=sa.String(length=50),
                              type_=sa.VARCHAR(length=100),
                              existing_nullable=False)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('attributes',
                              existing_type=postgresql.JSONB(
                                  astext_type=sa.Text()),
                              type_=sa.VARCHAR(),
                              existing_nullable=True)
        batch_op.alter_column('image',
                              existing_type=sa.String(length=120),
                              type_=sa.VARCHAR(length=200),
                              existing_nullable=True)
        batch_op.alter_column('name',
                              existing_type=sa.String(length=50),
                              type_=sa.VARCHAR(length=100),
                              existing_nullable=False)

    # ### end Alembic commands ###
